### ISSUE TITLE
Add descriptions in the lessons

### ISSUE THREAD

**Issue by Nikos1508** [simplified-coding/simplified-coding#119] opened 2023-11-16 15:39 UTC
**Is your feature request related to a problem? Please describe.**
We have to describe what every lesson is for. 

**Additional context**
![image](https://github.com/simplified-coding/simplified-coding/assets/113199464/85000294-f7ef-44b3-9148-f23dbc71cd4c)

**Comment by odysseuskir** [comment] 2023-11-16 20:21
Duplicate of #114

**Closed by odysseuskir** 2023-11-16 20:21 UTC
Labels: enhancement

**Comment by GalaxyGamingBoy** [comment] 2023-11-16 23:10
I digress, the issue clearly means the courses.json not the page

**Comment by GalaxyGamingBoy** [comment] 2023-11-16 23:11
Actually nvm, i will just rephrase the other one

**Comment by odysseuskir** [comment] 2023-11-17 13:57
💀
